### ISSUE TITLE
[metallb] add new arg for the common use case of `prefsrc`

### ISSUE THREAD

**Issue by sed-i** [canonical/microk8s-core-addons#146]
In local dev and CI we always<sup>[[1](https://juju.is/tutorials/lma-light#2-configure-microk8s), [2](https://github.com/canonical/traefik-k8s-operator/blob/a1e39d1ce2964d3ef554978588a1994834f110bf/tests/integration/helpers.py#L23), [3](https://github.com/canonical/cos-lite-bundle/blob/b3051bb8ea50af1edf55563a48387f64cd90c868/tests/load/gcp/cos-lite/runcmd.tpl.sh#L48)]</sup> enable metallb with 

```bash
IPADDR=$(ip -4 -j route get 2.2.2.2 | jq -r '.[] | .prefsrc')
microk8s enable metallb:$IPADDR-$IPADDR
```

I was hoping this fairly common use case could have its own arg for better DevX.

For example:
```
microk8s enable metallb:prefsrc
```

**Comment by rbarry82** [comment]
👍 

For a little clarity, it's somewhat of:

### As a user/developer, I want to easily enable access to applications running on Microk8s without `NodePort`

This is already documented, a little, but the level of knowledge, Googling, other which a user/administrator must have in order to know that "yes, using the same IP range as my host system won't break anything in the average use case (or that the actual range doesn't really matter as long as it's routable, so that pretty much any range would work from the host itself), yes a single address can be used as long as it's the only intersection in that range, ..." is surprisingly high.

I'm not sure that `prefsrc` is the right verb for it, but something which gives a little indication to the user "I'd like to use my host's IP address" (really, their default egress IP; this lookup would fail in systems which have no route to the internet, may behave strangely on systems with bonded NICs, may behave strangely on laptops where users swap back and forth between wired and wireless, but is a reasonably safe failover which won't pick `docker0` or `virbr0` or `lxd0`).

**Comment by neoaggelos** [comment]
Hi @rbarry82 @sed-i

If this is intended for local development and CI, where environments are typically single-node, then picking any IP address will do for your use case, and traffic will be routed accordingly, e.g.

```
microk8s enable metallb:10.100.100.100-10.100.100.100
```

Other nodes in the same network may not be able to reach this IP, but from my understanding this is not a requirement for CI and dev environments, is it?

I am not against having this particular functionality, I am simply a bit worried because it feels like we are trying to solve the wrong problem here.

Can you share some more background on your specific use case where the above would not suffice? Thanks!

**Comment by neoaggelos** [comment]
Yeah, it seems we are in consensus then, that it's more of a UX thing.

You also see me being a bit reluctant to do this because in the scenario you are describing you only need one LoadBalancer service. However, MetalLB will not re-use the same IP if more LoadBalancer services are created, so we are then found to a second problem.

As a new developer/k8s admin, I read the docs that I can do this trick to use MetalLB locally, then spin up my workloads, create 2 loadbalancers and get stuck because only one of them gets an IP address.

That said, I do see your point: I believe we can add a small section to https://microk8s.io/docs/addon-metallb to describe what is possible. What do you think?
